# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
01:
  ID: 1
  Return_Delay_Time: 0
02:
  ID: 2
  Return_Delay_Time: 0
03:
  ID: 3
  Return_Delay_Time: 0
04:
  ID: 4
  Return_Delay_Time: 0
05:
  ID: 5
  Return_Delay_Time: 0
06:
  ID: 6
  Return_Delay_Time: 0
07:
  ID: 7
  Return_Delay_Time: 0
08:
  ID: 8
  Return_Delay_Time: 0
09:
  ID: 9
  Return_Delay_Time: 0
10:
  ID: 10
  Return_Delay_Time: 0
11:
  ID: 11
  Return_Delay_Time: 0
12:
  ID: 12
  Return_Delay_Time: 0
13:
  ID: 13
  Return_Delay_Time: 0
14:
  ID: 14
  Return_Delay_Time: 0
15:
  ID: 15
  Return_Delay_Time: 0
